#!/bin/bash
set -euo pipefail

source /home/kik/openfoam/OpenFOAM-v2512/etc/bashrc

cd "$(dirname "$0")"
blockMesh | tee logs/blockMesh.log
snappyHexMesh -overwrite | tee logs/snappyHexMesh.log
checkMesh | tee logs/checkMesh.log
setExprFields | tee logs/setExprFields.log
pimpleFoam | tee logs/pimpleFoam.log
